export const commonCodes: Record<string, string> = {
  japan: "TYO",
  india: "DEL",
  usa: "JFK",
  "united states": "JFK",
  "united kingdom": "LHR",
  france: "CDG",
  germany: "FRA",
  canada: "YYZ",
  australia: "SYD",
  uae: "DXB",
  dubai: "DXB",
  singapore: "SIN",
  thailand: "BKK",
  bangkok: "BKK",
  china: "PEK",
  beijing: "PEK",
  "new york": "JFK",
  nyc: "JFK",
  london: "LHR",
  paris: "CDG",
  frankfurt: "FRA",
  sydney: "SYD",
  toronto: "YYZ",
  tokyo: "TYO",
  osaka: "KIX",
  "hong kong": "HKG",
  shanghai: "PVG",
  seoul: "ICN",
  moscow: "SVO",
  rome: "FCO",

  nrt: "NRT",
  narita: "NRT",
  hnd: "HND",
  haneda: "HND",
  kix: "KIX",
  kansai: "KIX",
  ngo: "NGO",
  chubu: "NGO",
  fuk: "FUK",
  fukuoka: "FUK",
  cts: "CTS",
  sapporo: "CTS",
  delhi: "DEL",
  "new delhi": "DEL",
  mumbai: "BOM",
  bombay: "BOM",
  chennai: "MAA",
  madras: "MAA",
  bangalore: "BLR",
  bengaluru: "BLR",
  hyderabad: "HYD",
  kolkata: "CCU",
  calcutta: "CCU",
  ahmedabad: "AMD",
  pune: "PNQ",
  kochi: "COK",
  cochin: "COK",
  goa: "GOI",
  igi: "DEL",
  "indira gandhi": "DEL",
  t3: "DEL",
  cst: "BOM",
  csmia: "BOM",
  sahar: "BOM",
  kempegowda: "BLR",
  "electronic city": "BLR",
  anna: "MAA",
  meenambakkam: "MAA",
  "rajiv gandhi": "HYD",
  shamshabad: "HYD",
  ernakulam: "COK",
  nedumbassery: "COK",
  trivandrum: "TRV",
  thiruvananthapuram: "TRV",
  coimbatore: "CJB",
  madurai: "IXM",
  mangalore: "IXE",
  visakhapatnam: "VTZ",
  vizag: "VTZ",
  tiruchirappalli: "TRZ",
  "sardar patel": "AMD",
  lohegaon: "PNQ",
  dabolim: "GOI",
  mopa: "GOX",
  surat: "STV",
  rajkot: "RAJ",
  vadodara: "BDQ",
  baroda: "BDQ",
  nagpur: "NAG",
  aurangabad: "IXU",
  nashik: "ISK",
  chandigarh: "IXC",
  mohali: "IXC",
  jaipur: "JAI",
  amritsar: "ATQ",
  "golden temple": "ATQ",
  lucknow: "LKO",
  amausi: "LKO",
  varanasi: "VNS",
  banaras: "VNS",
  dehradun: "DED",
  "jolly grant": "DED",
  srinagar: "SXR",
  jammu: "IXJ",
  leh: "IXL",
  ladakh: "IXL",
  "netaji subhas": "CCU",
  "dum dum": "CCU",
  guwahati: "GAU",
  lokpriya: "GAU",
  patna: "PAT",
  jayprakash: "PAT",
  ranchi: "IXR",
  "birsa munda": "IXR",
  bhubaneswar: "BBI",
  "biju patnaik": "BBI",
  indore: "IDR",
  "devi ahilya": "IDR",
  bhopal: "BHO",
  "raja bhoj": "BHO",
  raipur: "RPR",
  "swami vivekananda": "RPR",
  imphal: "IMF",
  agartala: "IXA",
  aizawl: "AJL",
  dimapur: "DMU",
  silchar: "IXS",
  "port blair": "IXZ",
  andaman: "IXZ",
  kavaratti: "LRK",
  lakshadweep: "LRK",
  vijayawada: "VGA",
  tirupati: "TIR",
  rajahmundry: "RJA",
  belgaum: "IXG",
  hubli: "HBX",
  mysore: "MYQ",
  kannur: "CNN",
  "kannur international": "CNN",
  kullu: "KUU",
  manali: "KUU",
  dharamshala: "DHM",
  udaipur: "UDR",
  "maharana pratap": "UDR",
  jodhpur: "JDH",
  bikaner: "BKB",
  kota: "KTU",
  doha: "DOH",
  qatar: "DOH",
  "abu dhabi": "AUH",
  muscat: "MCT",
  oman: "MCT",
  bahrain: "BAH",
  kuwait: "KWI",
  riyadh: "RUH",
  jeddah: "JED",
  "kuala lumpur": "KUL",
  malaysia: "KUL",
  jakarta: "CGK",
  indonesia: "CGK",
  manila: "MNL",
  philippines: "MNL",
  "ho chi minh": "SGN",
  saigon: "SGN",
  hanoi: "HAN",
  vietnam: "HAN",
  amsterdam: "AMS",
  schiphol: "AMS",
  munich: "MUC",
  zurich: "ZRH",
  geneva: "GVA",
  madrid: "MAD",
  barcelona: "BCN",
  milan: "MXP",
};

export const commonAirports = [

  {
    iataCode: "DEL",
    name: "Indira Gandhi International Airport",
    city: "Delhi",
  },
  {
    iataCode: "BOM",
    name: "Chhatrapati Shivaji Maharaj International Airport",
    city: "Mumbai",
  },
  { iataCode: "MAA", name: "Chennai International Airport", city: "Chennai" },
  {
    iataCode: "BLR",
    name: "Kempegowda International Airport",
    city: "Bengaluru",
  },
  {
    iataCode: "HYD",
    name: "Rajiv Gandhi International Airport",
    city: "Hyderabad",
  },
  {
    iataCode: "CCU",
    name: "Netaji Subhas Chandra Bose International Airport",
    city: "Kolkata",
  },
  {
    iataCode: "AMD",
    name: "Sardar Vallabhbhai Patel International Airport",
    city: "Ahmedabad",
  },
  { iataCode: "PNQ", name: "Pune International Airport", city: "Pune" },
  { iataCode: "GOI", name: "Dabolim Airport", city: "Goa" },
  { iataCode: "COK", name: "Cochin International Airport", city: "Kochi" },
  {
    iataCode: "TRV",
    name: "Trivandrum International Airport",
    city: "Thiruvananthapuram",
  },
  {
    iataCode: "LKO",
    name: "Chaudhary Charan Singh International Airport",
    city: "Lucknow",
  },
  {
    iataCode: "GAU",
    name: "Lokpriya Gopinath Bordoloi International Airport",
    city: "Guwahati",
  },
  { iataCode: "PAT", name: "Jay Prakash Narayan Airport", city: "Patna" },
  {
    iataCode: "IXC",
    name: "Chandigarh International Airport",
    city: "Chandigarh",
  },
  { iataCode: "JAI", name: "Jaipur International Airport", city: "Jaipur" },
  {
    iataCode: "VNS",
    name: "Lal Bahadur Shastri International Airport",
    city: "Varanasi",
  },
  { iataCode: "IDR", name: "Devi Ahilya Bai Holkar Airport", city: "Indore" },
  { iataCode: "BDQ", name: "Vadodara Airport", city: "Vadodara" },
  { iataCode: "BHO", name: "Raja Bhoj Airport", city: "Bhopal" },
  {
    iataCode: "NAG",
    name: "Dr. Babasaheb Ambedkar International Airport",
    city: "Nagpur",
  },
  {
    iataCode: "IXE",
    name: "Mangalore International Airport",
    city: "Mangalore",
  },
  {
    iataCode: "VTZ",
    name: "Visakhapatnam International Airport",
    city: "Visakhapatnam",
  },
  {
    iataCode: "ATQ",
    name: "Sri Guru Ram Dass Jee International Airport",
    city: "Amritsar",
  },
  { iataCode: "IXB", name: "Bagdogra International Airport", city: "Siliguri" },
  { iataCode: "IXR", name: "Birsa Munda Airport", city: "Ranchi" },
  {
    iataCode: "BBI",
    name: "Biju Patnaik International Airport",
    city: "Bhubaneswar",
  },
  {
    iataCode: "CJB",
    name: "Coimbatore International Airport",
    city: "Coimbatore",
  },
  { iataCode: "IXJ", name: "Jammu Airport", city: "Jammu" },
  {
    iataCode: "SXR",
    name: "Sheikh ul-Alam International Airport",
    city: "Srinagar",
  },
  {
    iataCode: "IXZ",
    name: "Veer Savarkar International Airport",
    city: "Port Blair",
  },

  { iataCode: "NRT", name: "Narita International Airport", city: "Tokyo" },
  { iataCode: "HND", name: "Haneda Airport", city: "Tokyo" },
  { iataCode: "KIX", name: "Kansai International Airport", city: "Osaka" },
  {
    iataCode: "NGO",
    name: "Chubu Centrair International Airport",
    city: "Nagoya",
  },
  { iataCode: "FUK", name: "Fukuoka Airport", city: "Fukuoka" },
  { iataCode: "CTS", name: "New Chitose Airport", city: "Sapporo" },
  { iataCode: "OKA", name: "Naha Airport", city: "Okinawa" },

  {
    iataCode: "JFK",
    name: "John F. Kennedy International Airport",
    city: "New York",
  },
  {
    iataCode: "LAX",
    name: "Los Angeles International Airport",
    city: "Los Angeles",
  },
  { iataCode: "ORD", name: "O'Hare International Airport", city: "Chicago" },
  {
    iataCode: "SFO",
    name: "San Francisco International Airport",
    city: "San Francisco",
  },
  {
    iataCode: "DFW",
    name: "Dallas/Fort Worth International Airport",
    city: "Dallas",
  },
  {
    iataCode: "ATL",
    name: "Hartsfield-Jackson Atlanta International Airport",
    city: "Atlanta",
  },
  { iataCode: "MIA", name: "Miami International Airport", city: "Miami" },
  {
    iataCode: "SEA",
    name: "Seattle-Tacoma International Airport",
    city: "Seattle",
  },
  { iataCode: "LHR", name: "Heathrow Airport", city: "London" },
  { iataCode: "CDG", name: "Charles de Gaulle Airport", city: "Paris" },
  { iataCode: "FRA", name: "Frankfurt Airport", city: "Frankfurt" },
  { iataCode: "AMS", name: "Amsterdam Airport Schiphol", city: "Amsterdam" },
  { iataCode: "MUC", name: "Munich Airport", city: "Munich" },
  { iataCode: "ZRH", name: "Zurich Airport", city: "Zurich" },
  {
    iataCode: "FCO",
    name: "Leonardo da Vinci–Fiumicino Airport",
    city: "Rome",
  },
  {
    iataCode: "MAD",
    name: "Adolfo Suárez Madrid–Barajas Airport",
    city: "Madrid",
  },
  { iataCode: "BCN", name: "Barcelona–El Prat Airport", city: "Barcelona" },
  { iataCode: "IST", name: "Istanbul Airport", city: "Istanbul" },

  { iataCode: "DXB", name: "Dubai International Airport", city: "Dubai" },
  {
    iataCode: "AUH",
    name: "Abu Dhabi International Airport",
    city: "Abu Dhabi",
  },
  { iataCode: "DOH", name: "Hamad International Airport", city: "Doha" },
  { iataCode: "BAH", name: "Bahrain International Airport", city: "Bahrain" },
  {
    iataCode: "RUH",
    name: "King Khalid International Airport",
    city: "Riyadh",
  },
  {
    iataCode: "JED",
    name: "King Abdulaziz International Airport",
    city: "Jeddah",
  },

  { iataCode: "SIN", name: "Changi Airport", city: "Singapore" },
  { iataCode: "BKK", name: "Suvarnabhumi Airport", city: "Bangkok" },
  {
    iataCode: "KUL",
    name: "Kuala Lumpur International Airport",
    city: "Kuala Lumpur",
  },
  {
    iataCode: "CGK",
    name: "Soekarno–Hatta International Airport",
    city: "Jakarta",
  },
  {
    iataCode: "MNL",
    name: "Ninoy Aquino International Airport",
    city: "Manila",
  },
  {
    iataCode: "HKG",
    name: "Hong Kong International Airport",
    city: "Hong Kong",
  },
  { iataCode: "ICN", name: "Incheon International Airport", city: "Seoul" },
  {
    iataCode: "PVG",
    name: "Shanghai Pudong International Airport",
    city: "Shanghai",
  },
  {
    iataCode: "PEK",
    name: "Beijing Capital International Airport",
    city: "Beijing",
  },
  {
    iataCode: "CAN",
    name: "Guangzhou Baiyun International Airport",
    city: "Guangzhou",
  },

  { iataCode: "SYD", name: "Sydney Airport", city: "Sydney" },
  { iataCode: "MEL", name: "Melbourne Airport", city: "Melbourne" },
  { iataCode: "BNE", name: "Brisbane Airport", city: "Brisbane" },
  { iataCode: "PER", name: "Perth Airport", city: "Perth" },
  { iataCode: "ADL", name: "Adelaide Airport", city: "Adelaide" },

  {
    iataCode: "YYZ",
    name: "Toronto Pearson International Airport",
    city: "Toronto",
  },
  {
    iataCode: "YVR",
    name: "Vancouver International Airport",
    city: "Vancouver",
  },
  {
    iataCode: "YUL",
    name: "Montréal–Trudeau International Airport",
    city: "Montreal",
  },
  { iataCode: "YYC", name: "Calgary International Airport", city: "Calgary" },

  { iataCode: "AKL", name: "Auckland Airport", city: "Auckland" },
  {
    iataCode: "CPT",
    name: "Cape Town International Airport",
    city: "Cape Town",
  },
  {
    iataCode: "JNB",
    name: "O. R. Tambo International Airport",
    city: "Johannesburg",
  },
  {
    iataCode: "GRU",
    name: "São Paulo/Guarulhos International Airport",
    city: "São Paulo",
  },
  {
    iataCode: "EZE",
    name: "Ministro Pistarini International Airport",
    city: "Buenos Aires",
  },
  {
    iataCode: "SCL",
    name: "Arturo Merino Benítez International Airport",
    city: "Santiago",
  },

  { iataCode: "IXU", name: "Aurangabad Airport", city: "Aurangabad" },
  { iataCode: "RPR", name: "Swami Vivekananda Airport", city: "Raipur" },
  { iataCode: "STV", name: "Surat International Airport", city: "Surat" },
  { iataCode: "IXD", name: "Bamrauli Air Force Station", city: "Allahabad" },
  { iataCode: "DED", name: "Dehradun Airport", city: "Dehradun" },
  { iataCode: "DHM", name: "Kangra Airport", city: "Dharamshala" },
  { iataCode: "UDR", name: "Maharana Pratap Airport", city: "Udaipur" },
  { iataCode: "JDH", name: "Jodhpur Airport", city: "Jodhpur" },
  { iataCode: "KNU", name: "Kanpur Airport", city: "Kanpur" },
  { iataCode: "GAY", name: "Gaya Airport", city: "Gaya" },
];

export const airlineNames: Record<string, string> = {
  AI: "Air India",
  "6E": "IndiGo",
  SG: "SpiceJet",
  UK: "Vistara",
  G8: "Go First",
  IX: "Air India Express",
  LH: "Lufthansa",
  EK: "Emirates",
  QR: "Qatar Airways",
  SQ: "Singapore Airlines",
  BA: "British Airways",
  // add more as needed...
};

export function getAirlineName(code: string): string {
  return airlineNames[code] || code; 
}









// lib/cityNames.ts

export interface Airport {
  iataCode: string;
  city: string;
  name: string;
  country: string;
}

export const commonCity: Airport[] = [
  { iataCode: "DEL", city: "Delhi", name: "Indira Gandhi International Airport", country: "India" },
  { iataCode: "BOM", city: "Mumbai", name: "Chhatrapati Shivaji Maharaj International Airport", country: "India" },
  { iataCode: "BLR", city: "Bengaluru", name: "Kempegowda International Airport", country: "India" },
  { iataCode: "MAA", city: "Chennai", name: "Chennai International Airport", country: "India" },
  { iataCode: "HYD", city: "Hyderabad", name: "Rajiv Gandhi International Airport", country: "India" },
  { iataCode: "CCU", city: "Kolkata", name: "Netaji Subhas Chandra Bose International Airport", country: "India" },
  { iataCode: "DXB", city: "Dubai", name: "Dubai International Airport", country: "UAE" },
  { iataCode: "SIN", city: "Singapore", name: "Singapore Changi Airport", country: "Singapore" },
  { iataCode: "BKK", city: "Bangkok", name: "Suvarnabhumi Airport", country: "Thailand" },
  { iataCode: "KUL", city: "Kuala Lumpur", name: "Kuala Lumpur International Airport", country: "Malaysia" },
  { iataCode: "LHR", city: "London", name: "Heathrow Airport", country: "UK" },
  { iataCode: "JFK", city: "New York", name: "John F. Kennedy International Airport", country: "USA" },
  { iataCode: "LAX", city: "Los Angeles", name: "Los Angeles International Airport", country: "USA" },
  { iataCode: "CDG", city: "Paris", name: "Charles de Gaulle Airport", country: "France" },
  { iataCode: "FRA", city: "Frankfurt", name: "Frankfurt Airport", country: "Germany" },
  { iataCode: "SYD", city: "Sydney", name: "Sydney Airport", country: "Australia" },
  { iataCode: "ICN", city: "Seoul", name: "Incheon International Airport", country: "South Korea" },
  { iataCode: "NRT", city: "Tokyo", name: "Narita International Airport", country: "Japan" },
  { iataCode: "HND", city: "Tokyo", name: "Haneda Airport", country: "Japan" },
  { iataCode: "PEK", city: "Beijing", name: "Beijing Capital International Airport", country: "China" },
  { iataCode: "PVG", city: "Shanghai", name: "Shanghai Pudong International Airport", country: "China" },
  { iataCode: "AMS", city: "Amsterdam", name: "Amsterdam Airport Schiphol", country: "Netherlands" },
  { iataCode: "MAD", city: "Madrid", name: "Adolfo Suárez Madrid–Barajas Airport", country: "Spain" },
  { iataCode: "BCN", city: "Barcelona", name: "Barcelona–El Prat Airport", country: "Spain" },
  { iataCode: "FCO", city: "Rome", name: "Leonardo da Vinci–Fiumicino Airport", country: "Italy" },
  { iataCode: "MXP", city: "Milan", name: "Malpensa Airport", country: "Italy" },
  { iataCode: "ZRH", city: "Zurich", name: "Zurich Airport", country: "Switzerland" },
  { iataCode: "CPH", city: "Copenhagen", name: "Copenhagen Airport", country: "Denmark" },
  { iataCode: "ARN", city: "Stockholm", name: "Stockholm Arlanda Airport", country: "Sweden" },
  { iataCode: "OSL", city: "Oslo", name: "Oslo Airport", country: "Norway" },
  { iataCode: "HEL", city: "Helsinki", name: "Helsinki Airport", country: "Finland" },
  { iataCode: "DOH", city: "Doha", name: "Hamad International Airport", country: "Qatar" },
  { iataCode: "AUH", city: "Abu Dhabi", name: "Abu Dhabi International Airport", country: "UAE" },
  { iataCode: "IST", city: "Istanbul", name: "Istanbul Airport", country: "Turkey" },
  { iataCode: "YYZ", city: "Toronto", name: "Toronto Pearson International Airport", country: "Canada" },
  { iataCode: "YVR", city: "Vancouver", name: "Vancouver International Airport", country: "Canada" },
  { iataCode: "DXB", city: "Dubai", name: "Dubai International Airport", country: "UAE" },
  { iataCode: "SFO", city: "San Francisco", name: "San Francisco International Airport", country: "USA" },
  { iataCode: "ORD", city: "Chicago", name: "O'Hare International Airport", country: "USA" },
  { iataCode: "DFW", city: "Dallas", name: "Dallas/Fort Worth International Airport", country: "USA" },
  { iataCode: "ATL", city: "Atlanta", name: "Hartsfield-Jackson Atlanta International Airport", country: "USA" },
  { iataCode: "MIA", city: "Miami", name: "Miami International Airport", country: "USA" },
  { iataCode: "SEA", city: "Seattle", name: "Seattle–Tacoma International Airport", country: "USA" },
  { iataCode: "BOS", city: "Boston", name: "Logan International Airport", country: "USA" },
  { iataCode: "EWR", city: "Newark", name: "Newark Liberty International Airport", country: "USA" },
  { iataCode: "IAD", city: "Washington", name: "Washington Dulles International Airport", country: "USA" },
  { iataCode: "HKG", city: "Hong Kong", name: "Hong Kong International Airport", country: "China" },
  { iataCode: "TPE", city: "Taipei", name: "Taoyuan International Airport", country: "Taiwan" },
  { iataCode: "BWN", city: "Bandar Seri Begawan", name: "Brunei International Airport", country: "Brunei" },
  { iataCode: "DPS", city: "Denpasar", name: "Ngurah Rai International Airport", country: "Indonesia" },
  { iataCode: "CGK", city: "Jakarta", name: "Soekarno–Hatta International Airport", country: "Indonesia" },
  { iataCode: "MNL", city: "Manila", name: "Ninoy Aquino International Airport", country: "Philippines" },
  { iataCode: "BNE", city: "Brisbane", name: "Brisbane Airport", country: "Australia" },
  { iataCode: "MEL", city: "Melbourne", name: "Melbourne Airport", country: "Australia" },
  { iataCode: "PER", city: "Perth", name: "Perth Airport", country: "Australia" },
  { iataCode: "AKL", city: "Auckland", name: "Auckland Airport", country: "New Zealand" },
  { iataCode: "WLG", city: "Wellington", name: "Wellington Airport", country: "New Zealand" },
  { iataCode: "CPT", city: "Cape Town", name: "Cape Town International Airport", country: "South Africa" },
  { iataCode: "JNB", city: "Johannesburg", name: "O.R. Tambo International Airport", country: "South Africa" },
  { iataCode: "MRU", city: "Port Louis", name: "Sir Seewoosagur Ramgoolam International Airport", country: "Mauritius" },
  { iataCode: "DKR", city: "Dakar", name: "Blaise Diagne International Airport", country: "Senegal" },
  { iataCode: "CMN", city: "Casablanca", name: "Mohammed V International Airport", country: "Morocco" },
  { iataCode: "CAI", city: "Cairo", name: "Cairo International Airport", country: "Egypt" },
  { iataCode: "BEY", city: "Beirut", name: "Beirut–Rafic Hariri International Airport", country: "Lebanon" },
  { iataCode: "TLV", city: "Tel Aviv", name: "Ben Gurion Airport", country: "Israel" },
  { iataCode: "RUH", city: "Riyadh", name: "King Khalid International Airport", country: "Saudi Arabia" },
  { iataCode: "JED", city: "Jeddah", name: "King Abdulaziz International Airport", country: "Saudi Arabia" },
  { iataCode: "BAH", city: "Manama", name: "Bahrain International Airport", country: "Bahrain" },
  { iataCode: "KWI", city: "Kuwait City", name: "Kuwait International Airport", country: "Kuwait" },
  { iataCode: "MCT", city: "Muscat", name: "Muscat International Airport", country: "Oman" },
  { iataCode: "SJJ", city: "Sarajevo", name: "Sarajevo International Airport", country: "Bosnia and Herzegovina" },
  { iataCode: "BEG", city: "Belgrade", name: "Belgrade Nikola Tesla Airport", country: "Serbia" },
  { iataCode: "BUD", city: "Budapest", name: "Budapest Ferenc Liszt International Airport", country: "Hungary" },
  { iataCode: "PRG", city: "Prague", name: "Václav Havel Airport Prague", country: "Czech Republic" },
  { iataCode: "VIE", city: "Vienna", name: "Vienna International Airport", country: "Austria" },
  { iataCode: "WAW", city: "Warsaw", name: "Warsaw Chopin Airport", country: "Poland" },
  { iataCode: "KBP", city: "Kyiv", name: "Boryspil International Airport", country: "Ukraine" },
  { iataCode: "SVO", city: "Moscow", name: "Sheremetyevo International Airport", country: "Russia" },
  { iataCode: "DME", city: "Moscow", name: "Domodedovo International Airport", country: "Russia" },
  { iataCode: "LED", city: "Saint Petersburg", name: "Pulkovo Airport", country: "Russia" },
  { iataCode: "DUB", city: "Dublin", name: "Dublin Airport", country: "Ireland" },
  { iataCode: "MAN", city: "Manchester", name: "Manchester Airport", country: "UK" },
  { iataCode: "EDI", city: "Edinburgh", name: "Edinburgh Airport", country: "UK" },
  { iataCode: "GLA", city: "Glasgow", name: "Glasgow Airport", country: "UK" },
  { iataCode: "BHX", city: "Birmingham", name: "Birmingham Airport", country: "UK" },
  { iataCode: "NCL", city: "Newcastle", name: "Newcastle International Airport", country: "UK" },
  { iataCode: "LIS", city: "Lisbon", name: "Lisbon Airport", country: "Portugal" },
  { iataCode: "OPO", city: "Porto", name: "Francisco de Sá Carneiro Airport", country: "Portugal" },
  { iataCode: "ATH", city: "Athens", name: "Athens International Airport", country: "Greece" },
  { iataCode: "SKG", city: "Thessaloniki", name: "Thessaloniki Airport", country: "Greece" },
  { iataCode: "RIX", city: "Riga", name: "Riga International Airport", country: "Latvia" },
  { iataCode: "VNO", city: "Vilnius", name: "Vilnius Airport", country: "Lithuania" },
  { iataCode: "TLL", city: "Tallinn", name: "Tallinn Airport", country: "Estonia" },
  { iataCode: "OTP", city: "Bucharest", name: "Henri Coandă International Airport", country: "Romania" },
  { iataCode: "SOF", city: "Sofia", name: "Sofia Airport", country: "Bulgaria" },
  { iataCode: "ZAG", city: "Zagreb", name: "Zagreb Airport", country: "Croatia" },
  { iataCode: "LJU", city: "Ljubljana", name: "Ljubljana Jože Pučnik Airport", country: "Slovenia" },
  { iataCode: "BRU", city: "Brussels", name: "Brussels Airport", country: "Belgium" },
  { iataCode: "LUX", city: "Luxembourg", name: "Luxembourg Airport", country: "Luxembourg" },
  { iataCode: "GVA", city: "Geneva", name: "Geneva Airport", country: "Switzerland" },
  { iataCode: "BSL", city: "Basel", name: "EuroAirport Basel-Mulhouse-Freiburg", country: "Switzerland" },
  { iataCode: "STR", city: "Stuttgart", name: "Stuttgart Airport", country: "Germany" },
  { iataCode: "MUC", city: "Munich", name: "Munich Airport", country: "Germany" },
  { iataCode: "TXL", city: "Berlin", name: "Berlin Tegel Airport", country: "Germany" },
  { iataCode: "HAM", city: "Hamburg", name: "Hamburg Airport", country: "Germany" },
  { iataCode: "CGN", city: "Cologne", name: "Cologne Bonn Airport", country: "Germany" },
  { iataCode: "DUS", city: "Düsseldorf", name: "Düsseldorf Airport", country: "Germany" },
  { iataCode: "NUE", city: "Nuremberg", name: "Nuremberg Airport", country: "Germany" },
  { iataCode: "LEJ", city: "Leipzig", name: "Leipzig/Halle Airport", country: "Germany" },
  { iataCode: "BRE", city: "Bremen", name: "Bremen Airport", country: "Germany" },
  { iataCode: "HAJ", city: "Hannover", name: "Hannover Airport", country: "Germany" },
  { iataCode: "DRS", city: "Dresden", name: "Dresden Airport", country: "Germany" },
  { iataCode: "FMO", city: "Münster", name: "Münster Osnabrück International Airport", country: "Germany" },
  { iataCode: "SCL", city: "Santiago", name: "Arturo Merino Benítez International Airport", country: "Chile" },
  { iataCode: "EZE", city: "Buenos Aires", name: "Ministro Pistarini International Airport", country: "Argentina" },
  { iataCode: "GRU", city: "São Paulo", name: "Guarulhos International Airport", country: "Brazil" },
  { iataCode: "GIG", city: "Rio de Janeiro", name: "Rio de Janeiro/Galeão International Airport", country: "Brazil" },
  { iataCode: "BSB", city: "Brasília", name: "Brasília International Airport", country: "Brazil" },
  { iataCode: "CNF", city: "Belo Horizonte", name: "Tancredo Neves International Airport", country: "Brazil" },
  { iataCode: "FOR", city: "Fortaleza", name: "Pinto Martins International Airport", country: "Brazil" },
  { iataCode: "REC", city: "Recife", name: "Recife/Guararapes International Airport", country: "Brazil" },
  { iataCode: "SSA", city: "Salvador", name: "Deputado Luís Eduardo Magalhães International Airport", country: "Brazil" },
  { iataCode: "POA", city: "Porto Alegre", name: "Salgado Filho International Airport", country: "Brazil" },
  { iataCode: "CWB", city: "Curitiba", name: "Afonso Pena International Airport", country: "Brazil" },
  { iataCode: "FLN", city: "Florianópolis", name: "Hercílio Luz International Airport", country: "Brazil" },
  { iataCode: "CGH", city: "São Paulo", name: "Congonhas Airport", country: "Brazil" },
  { iataCode: "CUN", city: "Cancún", name: "Cancún International Airport", country: "Mexico" },
  { iataCode: "MEX", city: "Mexico City", name: "Benito Juárez International Airport", country: "Mexico" },
  { iataCode: "GDL", city: "Guadalajara", name: "Miguel Hidalgo y Costilla International Airport", country: "Mexico" },
  { iataCode: "MTY", city: "Monterrey", name: "Monterrey International Airport", country: "Mexico" },
  { iataCode: "PTY", city: "Panama City", name: "Tocumen International Airport", country: "Panama" },
  { iataCode: "BOG", city: "Bogotá", name: "El Dorado International Airport", country: "Colombia" },
  { iataCode: "LIM", city: "Lima", name: "Jorge Chávez International Airport", country: "Peru" },
  { iataCode: "UIO", city: "Quito", name: "Mariscal Sucre International Airport", country: "Ecuador" },
  { iataCode: "GYE", city: "Guayaquil", name: "José Joaquín de Olmedo International Airport", country: "Ecuador" },
  { iataCode: "CCS", city: "Caracas", name: "Simón Bolívar International Airport", country: "Venezuela" },
  { iataCode: "SJU", city: "San Juan", name: "Luis Muñoz Marín International Airport", country: "Puerto Rico" },
  { iataCode: "NAS", city: "Nassau", name: "Lynden Pindling International Airport", country: "Bahamas" },
  { iataCode: "KIN", city: "Kingston", name: "Norman Manley International Airport", country: "Jamaica" },
  { iataCode: "MBJ", city: "Montego Bay", name: "Sangster International Airport", country: "Jamaica" },
  { iataCode: "SDQ", city: "Santo Domingo", name: "Las Américas International Airport", country: "Dominican Republic" },
  { iataCode: "PUJ", city: "Punta Cana", name: "Punta Cana International Airport", country: "Dominican Republic" },
  { iataCode: "SAL", city: "San Salvador", name: "Monseñor Óscar Arnulfo Romero International Airport", country: "El Salvador" },
  { iataCode: "TGU", city: "Tegucigalpa", name: "Toncontín International Airport", country: "Honduras" },
  { iataCode: "SAP", city: "San Pedro Sula", name: "Ramón Villeda Morales International Airport", country: "Honduras" },
  { iataCode: "MGA", city: "Managua", name: "Augusto C. Sandino International Airport", country: "Nicaragua" },
  { iataCode: "LIR", city: "Liberia", name: "Daniel Oduber Quirós International Airport", country: "Costa Rica" },
  { iataCode: "SJO", city: "San José", name: "Juan Santamaría International Airport", country: "Costa Rica" },
  { iataCode: "PTY", city: "Panama City", name: "Tocumen International Airport", country: "Panama" },
];

export function getCityName(iataCode: string): string {
  const airport = commonCity.find(a => a.iataCode === iataCode);
  return airport ? airport.city : iataCode;
}